# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: virt-who.spec

# add or remove files that should be synced
files_to_sync:
    - virt-who.spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: virt-who
# downstream (Fedora) RPM package name
downstream_package_name: virt-who
