#!/bin/sh

if [ -f ./libvirt-rhsm.py ];
then
    # Run it from local directory when available
    exec /usr/bin/python ./libvirt-rhsm.py "$@"
else
    # Run it from /usr/share/libvirt-rhsm
    exec /usr/bin/python /usr/share/libvirt-rhsm/libvirt-rhsm.py "$@"
fi
