#!/bin/sh

if [ -f ./virtwhopassword.py ];
then
    # Run it from local directory when available
    exec /usr/bin/python ./virtwhopassword.py "$@"
else
    # Run it from /usr/share/virt-who
    exec /usr/bin/python /usr/share/virt-who/virtwhopassword.py "$@"
fi
