.TH VIRT-WHO "8" "June 2014" "virt-who"
.SH NAME
virt-who-password - Utility that encrypts passwords for virt-who.
.SH SYNOPSIS
virt-who-password [-h|--help]
.SH USAGE
virt-who-password prompts for password and writes encrypted entered password
to the standard output.

This utility must be executed as root, because the encryption key is written
into file that is only readable by root. Note that root can decrypt the
password.

Encryption key is written into file \fB/var/lib/virt-who/key\fR, make sure
that this file is only readable and writable by root.
.SH AUTHOR
Radek Novacek <rnovacek at redhat dot com>

