#!/bin/sh

if [ -f ./virtwho/password/__main__.py ];
then
    # Run it from local directory when available
    exec /usr/bin/python -m virtwho.password "$@"
else
    # Run it from /usr/share/virt-who
    exec /usr/bin/python /usr/share/virt-who/virtwhopassword.py "$@"
fi
