#!/bin/sh

if [ -f ./virtwho.py ];
then
    # Run it from local directory when available
    exec /usr/bin/python ./virtwho.py "$@"
else
    # Run it from /usr/share/virt-who
    exec /usr/bin/python /usr/share/virt-who/virtwho.py "$@"
fi
