#!/bin/sh
#
# virt-who Agent for reporting virtual guest IDs to subscription-manager
#
# chkconfig:   2345 95 95
# description: Agent for reporting virtual guest IDs to subscription-manager

### BEGIN INIT INFO
# Provides:       virt-who
# Required-Start: $network libvirtd
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop virt-who
# Description: Agent for reporting virtual guest IDs to subscription-manager
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/virt-who"
prog="virt-who"
config="/etc/sysconfig/virt-who"
pidfile="/var/run/$prog.pid"

# Export all variables in /etc/sysconfig/virt-who
set -a
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
set +a

lockfile=/var/lock/subsys/virt-who

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --pidfile $pidfile $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?