#!/bin/sh

if [ -f ./satellite.py ];
then
    # Run it from local directory when available
    exec /usr/bin/python ./satellite.py "$@"
else
    # Run it from /usr/share/virt-who
    exec /usr/bin/python /usr/share/virt-who/satellite.py "$@"
fi
